### ISSUE TITLE
about {} in your article

### ISSUE THREAD

**Issue by chenglongzjg** [kangax/nfe#6]
the code in your article like below:

```
try {
  { "x": 5 }; // "{" and "}" are parsed as a block
} catch(err) {
  // SyntaxError
}
({ "x": 5 }); // grouping operator forces "{" and "}" to be parsed as object literal
```

how  `{ "x": 5 }; // "{" and "}" are parsed as a block` be parsed as a block ?
i ran it and the result like below:

```
> typeof ({"x": 5});
'object'
> typeof {"x": 5};
'object'
```

both of them are  `object`.
so what difference between them ?

**Comment by kangax** [comment]
`typeof ...` makes `...` an expression. That's why there's no difference in your example.

**Comment by chenglongzjg** [comment]
Blocks can only contain Statements.
but if  `{ "x": 5 }; // "{" and "}" are parsed as a block` , how can i understand  `"x":5` ？ 
when i ran it in node, like this:

```
> {"a":5}
{ a: 5 }
> ({"a":5})
{ a: 5 }
> 
```

**Comment by kangax** [comment]
The first one is a block with a label statement

**Comment by chenglongzjg** [comment]
ths a lot 😸

2016-06-02 22:53 GMT+08:00 Juriy Zaytsev notifications@github.com:
